# pants.toml
[GLOBAL]
pants_version = "2.27.0"


plugins = ["hdrhistogram"]


backend_packages = [
    "pants.core",
    "pants.backend.python",
    "pants.backend.docker",
    #"pants.backend.experimental.terraform",
    "pants.backend.experimental.python.lint.ruff.check",
]


pants_ignore = [
  "templates/**",
  "infra-packages/**", ## pants terraform managment is unstable
  "**/infra/**"
]

# Performance and caching
process_execution_local_parallelism = 4
process_execution_cache_namespace = "pants-cache"

[python]
interpreter_constraints = [">=3.12"]

# resolves in 3rdparty
enable_resolves = true
default_resolve = "python"

[python.resolves]
python = "3rdparty/python/python-deps.lock"
tools = "3rdparty/tools/tools-deps.lock"




[python-infer]
use_rust_parser = true
# Improve import inference
imports = true
string_imports = true
assets = true


[ruff]
config = "pyproject.toml"

[pytest]
config = "pyproject.toml"
execution_slot_var = "PANTS_EXECUTION_SLOT"
install_from_resolve = "tools"
requirements = ["//3rdparty/python:tools-reqs#pytest"]

#[download-terraform]
# 1. Specify the version you want to use.
#version = "1.13.0"
#extra_env_vars = ["PATH"]

# Source roots for better organization
[source]
root_patterns = [
    "/",
    "src",
    "tests",
    "packages",
    "services",
    "infra-packages",
    "ditty-bag",
    ".tflint.hcl",
]

# Anonymous telemetry (you can disable if preferred)
[anonymous-telemetry]
enabled = false

# Improved logging
[stats]
log = true
