[GLOBAL]
pants_version = "2.27.0"
backend_packages = [
    "pants.backend.python",
    "pants.backend.shell",
    "pants.backend.docker",
    "pants.backend.experimental.terraform",
]

# Performance and caching
process_execution_local_parallelism = 4
process_execution_cache_namespace = "pants-cache"

[python]
interpreter_constraints = [">=3.12"]
# Enable resolves for better dependency management
enable_resolves = true
default_resolve = "python-default"

[python-infer]
use_rust_parser = true
# Improve import inference
imports = true
string_imports = true
assets = true

[ruff]
config = "pyproject.toml"

[pytest]
config_discovery = true
execution_slot_var = "PANTS_EXECUTION_SLOT"

[shell-setup]
# For any shell scripts you might have
executable_search_paths = ["/bin", "/usr/bin", "/usr/local/bin"]

[docker]
# For your CI Dockerfile
default_repository = "{name}"
build_args = []

[download-terraform]
# Forward PATH for terraform to access git and other tools
extra_env_vars = ["PATH"]

# Source roots for better organization
[source]
root_patterns = [
    "src",
    "tests",
    "packages",
    "services",
    "infra-packages",
    "tools",
]

# Anonymous telemetry (you can disable if preferred)
[anonymous-telemetry]
enabled = false

# Improved logging
[stats]
log = true