# pants.toml
[GLOBAL]
pants_version = "2.27.0"
plugins = ["hdrhistogram"]
backend_packages = [
    "pants.backend.python",
    "pants.backend.docker",
    "pants.backend.experimental.terraform",
]


pants_ignore = [
  "templates/**",
]

# Performance and caching
process_execution_local_parallelism = 4
process_execution_cache_namespace = "pants-cache"

[python]
interpreter_constraints = [">=3.11"]
# Enable resolves for better dependency management
enable_resolves = true
resolves = ["python-default"]

[python-infer]
use_rust_parser = true
# Improve import inference
imports = true
string_imports = true
assets = true


[ruff]
config = "pyproject.toml"

[pytest]
config_discovery = true
execution_slot_var = "PANTS_EXECUTION_SLOT"


[docker]
# For your CI Dockerfile
default_repository = "{name}"
build_args = []

[download-terraform]
# 1. Specify the version you want to use.
version = "1.13.0"
extra_env_vars = ["PATH"]

# Source roots for better organization
[source]
root_patterns = [
    "src",
    "tests",
    "packages",
    "services",
    "infra-packages",
    "ditty-bag",
    ".tflint.hcl",
]

# Anonymous telemetry (you can disable if preferred)
[anonymous-telemetry]
enabled = false

# Improved logging
[stats]
log = true
