[GLOBAL]
pants_version = "2.27.0"
backend_packages = [
    "pants.backend.python",
    "pants.backend.docker",
    "pants.backend.experimental.terraform",
]


pants_ignore = [
  "templates/**",
]

# Performance and caching
process_execution_local_parallelism = 4
process_execution_cache_namespace = "pants-cache"

[subprocess-environment]
env_vars = ["PATH=/home/linuxbrew/.linuxbrew/bin:%(env.HOME)s/.linuxbrew/bin:/usr/local/bin:/usr/bin:%(env.PATH)s"]


[python]
interpreter_constraints = [">=3.12"]
# Enable resolves for better dependency management
enable_resolves = true
default_resolve = "python-default"

[python-infer]
use_rust_parser = true
# Improve import inference
imports = true
string_imports = true
assets = true

[ruff]
config = "pyproject.toml"

[pytest]
config_discovery = true
execution_slot_var = "PANTS_EXECUTION_SLOT"


[docker]
# For your CI Dockerfile
default_repository = "{name}"
build_args = []

[download-terraform]
# 1. Specify the version you want to use.
version = "1.13.0"
extra_env_vars = ["PATH"]

# 2. Append your custom version information to the known_versions list.
# Format: '<version>|<platform>|<sha256>|<size_in_bytes>'
known_versions.add = [
  "1.13.0|linux_x86_64|de8ef905f84f24675da202a6967fddc40b2b23c15fc92a5007570f46a9fcc104|30637270",
]


# Source roots for better organization
[source]
root_patterns = [
    "src",
    "tests",
    "packages",
    "services",
    "infra-packages",
    "tools",
]

# Anonymous telemetry (you can disable if preferred)
[anonymous-telemetry]
enabled = false

# Improved logging
[stats]
log = true
