[project]
name = "metaflow_qwen_pac"
version = "0.1.0"
description = "a quick proof of proccess finetune of metaflow with aws batch"
readme = "README.md"
requires-python = ">=3.12"

[tool.ruff]
# Same as Black.
line-length = 88
indent-width = 4
target-version = "py310"

# Exclude a variety of commonly ignored directories and the temporary
# file created by the setup-miniconda action.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "setup-miniconda-patched-*.yml", # Ignore conda temp files
    ".mypy_cache",
    ".pytest_cache",
    "docs",
    "notebooks",
    "sdist",
    "wheel",
    "*.egg-info",
]

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # Pyflakes
    "I",  # isort
    "C",  # flake8-comprehensions
    "B",  # flake8-bugbear
]

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"
