# .github/workflows/python-ci.yml
name: Python CI

on:
  pull_request:
    paths:
      - 'packages/**'
      - 'services/**'
      - 'BUILD'
      - 'BUILD_MACROS.py'
      - 'pants.toml'
      - 'pyproject.toml'
      - '3rdparty/**'
      - '.github/workflows/python-ci.yml'
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Perform Python CI Checks
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.11'

      - uses: pantsbuild/actions/init-pants@v10
        with:
          gha-cache-key: v1
          named-caches-hash: ${{ hashFiles('3rdparty/tools/tools-reqs.lock') }}

      - name: Setup tools with asdf
        uses: asdf-vm/actions/install@v4.0.0


      - name: Run Pants
        run: |
          pants \
            --changed-since=origin/main \
            tailor --check \
            update-build-files --check \
            lint

      - name: Upload pants log
        uses: actions/upload-artifact@v4
        with:
          name: pants-log
          path: .pants.d/workdir/pants.log
        if: always()
