# .github/workflows/terraform-ci.yml
name: Terraform CI

on:
  pull_request:
    paths:
      - 'infra-packages/**'
      - '.github/workflows/terraform-ci.yml'
      - '.pre-commit-config.yaml'
  push:
    branches: [ main ]
    paths:
      - 'infra-packages/**'
      - '.github/workflows/terraform-ci.yml'
      - '.pre-commit-config.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    name: Validate Terraform Modules
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - uses: pantsbuild/actions/init-pants@v10
        with:
          gha-cache-key: v1
          named-caches-hash: ${{ hashFiles('3rdparty/tools/tools-reqs.lock') }}

      - name: Setup tools with asdf
        uses: asdf-vm/actions/install@v4.0.0



      - name: Run pre-commit
        run: |
          # Run pre-commit for hooks like terraform-docs
          pre-commit run --all-files --show-diff-on-failure

      - name: Run Pants
        run: |
          pants \
            --changed-since=origin/main \
            tailor --check \
            update-build-files --check \
            lint

      - name: Upload pants log
        uses: actions/upload-artifact@v4
        with:
          name: pants-log
          path: .pants.d/workdir/pants.log
        if: always()
