# .github/workflows/terraform-ci.yml
name: Terraform CI

on:
  pull_request:
    paths:
      - 'infra-packages/**'
      - '.github/workflows/terraform-ci.yml'
      - '.pre-commit-config.yaml'
  push:
    branches: [ main ]
    paths:
      - 'infra-packages/**'
      - '.github/workflows/terraform-ci.yml'
      - '.pre-commit-config.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    name: Validate Terraform Modules
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.11'

      - uses: pantsbuild/actions/init-pants@v10
        with:
          gha-cache-key: v1
          named-caches-hash: ${{ hashFiles('3rdparty/tools/tools-reqs.lock') }}

      - name: Setup tools with asdf
        uses: asdf-vm/actions/setup@v3

      - name: Run pre-commit hooks
        run: |
          . "$HOME/.asdf/asdf.sh"
          pre-commit run --all-files --show-diff-on-failure
