name: Pants CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}-ci:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Pants and pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pants
            ~/.cache/pip
          key: ${{ runner.os }}-pants-${{ hashFiles('pants.toml', 'pyproject.toml', '3rdparty/python/default.lock') }}
          restore-keys: |
            ${{ runner.os }}-pants-

      - name: Bootstrap Pants
        run: |
          ./pants --version

      - name: Lint/Format (PR - changed only)
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          ./pants --changed-since=origin/${{ github.base_ref }} --changed-dependents=transitive fmt --check
          ./pants --changed-since=origin/${{ github.base_ref }} --changed-dependents=transitive lint

      - name: Test (PR - changed only)
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          ./pants --changed-since=origin/${{ github.base_ref }} --changed-dependents=transitive test

      - name: Lint/Format (push - all)
        if: ${{ github.event_name == 'push' }}
        run: |
          ./pants fmt --check ::
          ./pants lint ::

      - name: Test (push - all)
        if: ${{ github.event_name == 'push' }}
        run: |
          ./pants test ::
