name: Pants

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Perform CI Checks
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: pantsbuild/actions/init-pants@v8
        with:
          gha-cache-key: v1
          named-caches-hash: ${{ hashFiles('3rdparty/python/default.lock') }}
          cache-lmdb-store: 'true'
      - name: Check BUILD files
        run: |
          pants tailor --check ::
      - name: Lint and typecheck
        run: |
          pants lint check ::
      - name: Test
        run: |
          pants test ::
