name: Pants

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Perform CI Checks
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.11'
      - uses: pantsbuild/actions/init-pants@v10
        with:
          gha-cache-key: v1
          named-caches-hash: ${{ hashFiles('3rdparty/tools/tools-reqs.lock') }}
      - name: Check BUILD files
        run: |
          pants tailor
      - name: Lint and typecheck
        run: |
          pants lint
