name: Pants CI

on:
  pull_request:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-ci

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image_name: ${{ steps.image_name.outputs.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .github/ci.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Set image name output
        id: image_name
        run: echo "name=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}" >> $GITHUB_OUTPUT

  ci:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.build.outputs.image_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for Pants to compute changed files.

      - name: Cache Pants and pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pants
            ~/.cache/pip
          key: ${{ runner.os }}-pants-${{ hashFiles('pants.toml', 'pyproject.toml', '3rdparty/python/default.lock') }}
          restore-keys: |
            ${{ runner.os }}-pants-

      - name: Set Pants spec
        id: spec
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "spec=--changed-since=origin/${{ github.base_ref }} --changed-dependents=transitive" >> $GITHUB_OUTPUT
          else
            echo "spec=::" >> $GITHUB_OUTPUT
          fi

      - name: Run Pants
        run: |
          ./pants tailor --check ::
          ./pants --concurrent fmt --check ${{ steps.spec.outputs.spec }}
          ./pants --concurrent lint ${{ steps.spec.outputs.spec }}
          ./pants --concurrent test ${{ steps.spec.outputs.spec }}
