name: Terraform Modules CI

on:
  pull_request:
    paths:
      - 'infra-packages/**'
  push:
    branches: [ main ]
    paths:
      - 'infra-packages/**'

jobs:
  validate:
    name: Validate Terraform Modules
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.13'

      - uses: pantsbuild/actions/init-pants@v8
        with:
          gha-cache-key: v1
          named-caches-hash: ${{ hashFiles('3rdparty/tools/tools-reqs.lock') }}
          cache-lmdb-store: 'true'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.0
          terraform_wrapper: false

      - name: Tailor BUILD files
        run: |
          pants tailor --check ::

      - name: Lint Terraform
        run: |
          pants lint infra-packages::

      - name: Check Terraform
        run: |
          pants check infra-packages::

      - name: Test Terraform
        run: |
          pants test infra-packages::
