name: Terraform Modules CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'infra-packages/**'
      - '.github/workflows/validate-modules.yml'
  push:
    branches: [ main ]
    paths:
      - 'infra-packages/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}-ci:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for Pants to compute changed files.

      - name: Cache Pants, pip, and Terraform
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pants
            ~/.cache/pip
            /home/runner/.terraform.d/plugin-cache
          key: ${{ runner.os }}-pants-terraform-${{ hashFiles('pants.toml', 'pyproject.toml', '3rdparty/python/default.lock', '**/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-pants-terraform-

      - name: Set Pants spec
        id: spec
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "spec=--changed-since=origin/${{ github.base_ref }} --changed-dependents=transitive" >> $GITHUB_OUTPUT
          else
            echo "spec=::" >> $GITHUB_OUTPUT
          fi

      - name: Run Terraform validation
        env:
          TF_PLUGIN_CACHE_DIR: /home/runner/.terraform.d/plugin-cache
        run: |
          ./pants --concurrent lint ${{ steps.spec.outputs.spec }} infra-packages::
          ./pants --concurrent check ${{ steps.spec.outputs.spec }} infra-packages::
          ./pants --concurrent test ${{ steps.spec.outputs.spec }} infra-packages::
